/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PeerMatchRouteImport } from './routes/peer-match'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MoodTrackerRouteImport } from './routes/mood-tracker'
import { Route as CommunityQnaRouteImport } from './routes/community-qna'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VolunteerDashboardRouteImport } from './routes/volunteer/dashboard'
import { Route as AdminVolunteersRouteImport } from './routes/admin/volunteers'
import { Route as AdminCommandCenterRouteImport } from './routes/admin/command-center'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PeerMatchRoute = PeerMatchRouteImport.update({
  id: '/peer-match',
  path: '/peer-match',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodTrackerRoute = MoodTrackerRouteImport.update({
  id: '/mood-tracker',
  path: '/mood-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityQnaRoute = CommunityQnaRouteImport.update({
  id: '/community-qna',
  path: '/community-qna',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VolunteerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerDashboardRoute = VolunteerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => VolunteerRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/admin/volunteers',
  path: '/admin/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandCenterRoute = AdminCommandCenterRouteImport.update({
  id: '/admin/command-center',
  path: '/admin/command-center',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/community-qna': typeof CommunityQnaRoute
  '/mood-tracker': typeof MoodTrackerRoute
  '/partners': typeof PartnersRoute
  '/peer-match': typeof PeerMatchRoute
  '/resources': typeof ResourcesRoute
  '/volunteer': typeof VolunteerRouteWithChildren
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/community-qna': typeof CommunityQnaRoute
  '/mood-tracker': typeof MoodTrackerRoute
  '/partners': typeof PartnersRoute
  '/peer-match': typeof PeerMatchRoute
  '/resources': typeof ResourcesRoute
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/volunteer': typeof VolunteerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/check-in': typeof CheckInRoute
  '/community-qna': typeof CommunityQnaRoute
  '/mood-tracker': typeof MoodTrackerRoute
  '/partners': typeof PartnersRoute
  '/peer-match': typeof PeerMatchRoute
  '/resources': typeof ResourcesRoute
  '/volunteer': typeof VolunteerRouteWithChildren
  '/admin/command-center': typeof AdminCommandCenterRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/volunteer/dashboard': typeof VolunteerDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/check-in'
    | '/community-qna'
    | '/mood-tracker'
    | '/partners'
    | '/peer-match'
    | '/resources'
    | '/volunteer'
    | '/admin/command-center'
    | '/admin/volunteers'
    | '/volunteer/dashboard'
    | '/admin/'
    | '/volunteer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/check-in'
    | '/community-qna'
    | '/mood-tracker'
    | '/partners'
    | '/peer-match'
    | '/resources'
    | '/admin/command-center'
    | '/admin/volunteers'
    | '/volunteer/dashboard'
    | '/admin'
    | '/volunteer'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/check-in'
    | '/community-qna'
    | '/mood-tracker'
    | '/partners'
    | '/peer-match'
    | '/resources'
    | '/volunteer'
    | '/admin/command-center'
    | '/admin/volunteers'
    | '/volunteer/dashboard'
    | '/admin/'
    | '/volunteer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CheckInRoute: typeof CheckInRoute
  CommunityQnaRoute: typeof CommunityQnaRoute
  MoodTrackerRoute: typeof MoodTrackerRoute
  PartnersRoute: typeof PartnersRoute
  PeerMatchRoute: typeof PeerMatchRoute
  ResourcesRoute: typeof ResourcesRoute
  VolunteerRoute: typeof VolunteerRouteWithChildren
  AdminCommandCenterRoute: typeof AdminCommandCenterRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peer-match': {
      id: '/peer-match'
      path: '/peer-match'
      fullPath: '/peer-match'
      preLoaderRoute: typeof PeerMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood-tracker': {
      id: '/mood-tracker'
      path: '/mood-tracker'
      fullPath: '/mood-tracker'
      preLoaderRoute: typeof MoodTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-qna': {
      id: '/community-qna'
      path: '/community-qna'
      fullPath: '/community-qna'
      preLoaderRoute: typeof CommunityQnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/dashboard': {
      id: '/volunteer/dashboard'
      path: '/dashboard'
      fullPath: '/volunteer/dashboard'
      preLoaderRoute: typeof VolunteerDashboardRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/admin/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/command-center': {
      id: '/admin/command-center'
      path: '/admin/command-center'
      fullPath: '/admin/command-center'
      preLoaderRoute: typeof AdminCommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface VolunteerRouteChildren {
  VolunteerDashboardRoute: typeof VolunteerDashboardRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
}

const VolunteerRouteChildren: VolunteerRouteChildren = {
  VolunteerDashboardRoute: VolunteerDashboardRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
}

const VolunteerRouteWithChildren = VolunteerRoute._addFileChildren(
  VolunteerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CheckInRoute: CheckInRoute,
  CommunityQnaRoute: CommunityQnaRoute,
  MoodTrackerRoute: MoodTrackerRoute,
  PartnersRoute: PartnersRoute,
  PeerMatchRoute: PeerMatchRoute,
  ResourcesRoute: ResourcesRoute,
  VolunteerRoute: VolunteerRouteWithChildren,
  AdminCommandCenterRoute: AdminCommandCenterRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
